name: 🐛 Bug Report
description: Melde einen Bug in osCASH.me GATE
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Danke für deinen Bug Report! Bitte fülle alle Felder aus.
        
  - type: input
    id: version
    attributes:
      label: osCASH.me GATE Version
      description: Welche Version verwendest du?
      placeholder: v1.0.0-oscash-alpha.1
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Betroffene Komponente
      options:
        - Mobile Gateway
        - Web Interface  
        - Docker Setup
        - Payment Processing
        - API
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Beschreibung
      description: Beschreibe das Problem
    validations:
      required: true